# Generated by Django 5.2.7 on 2025-12-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_gen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("category", models.CharField(default="General", max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("original_data", models.JSONField(default=dict)),
            ],
        ),
    ]
