# Generated by Django 5.2.7 on 2025-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_gen", "0002_prompttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediageneration",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediageneration",
            name="hashtags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
