# Generated by Django 5.2.7 on 2025-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventormodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory_images/"
            ),
        ),
    ]
