# Generated by Django 5.2.7 on 2025-11-20 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventormodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventormodel",
            name="quantity_unit",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
