# Generated by Django 5.2.7 on 2025-11-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofilemodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofilemodel",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofilemodel",
            name="google_maps_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofilemodel",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="businessprofilemodel",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofilemodel",
            name="yelp_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="businessprofilemodel",
            name="business_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="socialmediaprofilemodel",
            name="media_type",
            field=models.CharField(default="image", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
