# Generated by Django 5.2.7 on 2025-11-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_businessprofilemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofilemodel',
            name='clover_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='merchant.businessprofilemodel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
