# Generated by Django 5.2.7 on 2025-12-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_businessprofilemodel_clover_connected_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfileModel",
        ),
    ]
