# Generated by Django 5.2.7 on 2025-11-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_uid', models.CharField(max_length=100, unique=True)),
                ('sale_date', models.DateField()),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer_flow', models.IntegerField()),
                ('weather_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_condition', models.CharField(max_length=100)),
                ('was_on_sale', models.BooleanField(default=False)),
                ('promotion_type', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flow_students', models.IntegerField(blank=True, null=True)),
                ('flow_family', models.IntegerField(blank=True, null=True)),
                ('flow_adults', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('holidays', models.ManyToManyField(blank=True, to='sales.salesholidaymodel')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventormodel')),
            ],
        ),
    ]
