# Generated by Django 5.2.7 on 2025-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingMetrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accuracy", models.FloatField()),
                ("loss", models.FloatField()),
                ("model_version", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
