# Generated by Django 5.2.7 on 2025-12-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_trainingmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmetrics',
            name='explained_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='mape',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='mse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='r2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
