# Generated by Django 5.2.7 on 2025-12-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_trainingmetrics_explained_variance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmetrics",
            name="training_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
